"use client";

import React from "react";
import NotificationsList from "@/components/monitor/NotificationsList";

export default function MonitorNotificationsPage() {
  return (
    <main className="p-6 max-w-4xl mx-auto">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-semibold">Monitor Notifications</h1>
          <p className="text-sm text-slate-500">App notifications generated by Monitor rules and events. Use Rules to control what generates alerts.</p>
        </div>
        <div className="flex gap-2">
          <a href="/dashboard/monitor/rules" className="px-3 py-2 rounded border text-sm">Manage Rules</a>
          <a href="/dashboard" className="px-3 py-2 rounded bg-amber-500 text-white text-sm">Back to Dashboard</a>
        </div>
      </div>

      <div className="rounded-2xl border bg-white p-4 shadow">
        <NotificationsList />
        <div className="mt-4 text-xs text-slate-500">
          If you see no notifications, create a watch and enable a simple rule (e.g., app_notification on change_detected), then trigger a check.
        </div>
      </div>
    </main>
  );
}
