-- Adds durable engine callback tracking columns for pipeline gating and debugging.
-- Use these instead of relying on JSON diagnostics merges.

alter table public.product_ingestions
  add column if not exists ingest_engine_status text,
  add column if not exists ingest_callback_at timestamptz,
  add column if not exists ingest_callback_request_id text,
  add column if not exists ingest_callback_payload jsonb;

comment on column public.product_ingestions.ingest_engine_status is
  'Status reported by ingest engine callback (e.g., completed/error).';
comment on column public.product_ingestions.ingest_callback_at is
  'Timestamp when callback was received and persisted.';
comment on column public.product_ingestions.ingest_callback_request_id is
  'Request id generated by callback endpoint for traceability.';
comment on column public.product_ingestions.ingest_callback_payload is
  'Trimmed callback payload snapshot (keys/previews/validation); avoid storing large raw bodies.';
