-- Add ingestion engine callback tracking columns.
-- These columns are intended to be written by the callback route (service role)
-- and used by pipeline gating/UI instead of relying on JSON diagnostics merges.

alter table public.product_ingestions
  add column if not exists ingest_engine_status text,
  add column if not exists ingest_callback_at timestamptz,
  add column if not exists ingest_callback_request_id text,
  add column if not exists ingest_callback_payload jsonb;

comment on column public.product_ingestions.ingest_engine_status is
  'Status reported by ingest engine callback (e.g., completed/error).';
comment on column public.product_ingestions.ingest_callback_at is
  'Timestamp when callback was received and persisted.';
comment on column public.product_ingestions.ingest_callback_request_id is
  'Request id generated by callback endpoint for traceability.';
comment on column public.product_ingestions.ingest_callback_payload is
  'Small/trimmed callback payload snapshot for debugging; do not store huge raw bodies.';
